@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('condownload_LOANS')
        {
            steps
            {
                script
                {
                     cicd.newdownload("maven.git")
                }
            }
        }
        stage('conbuild_LOANS')
        {
            steps
            {
                script
                {
                     cicd.newbuild()
                }
            }
        }
    }
} 
